### ISSUE TITLE
Plugin installed to /lib/jollywood/ directory, should be /lib/libretro/

### ISSUE THREAD

**Issue by apteryks** [libretro/bsnes-jg#1]
Hi,

Since this is a libretro plugin, my expectation would be that the core would be installed to under the `/lib/libretro/` directory, not `/lib/jollywood/` as the build system currently does. This is also not configurable; in `mk/jg.mk`, the `LIBPATH` variable reads:

```
override LIBPATH := $(LIBDIR)/jollywood
```

The `override` Make directive means this cannot be overridden.

Thanks for this promising work!

**Comment by carmiker** [comment]
The libretro build uses a completely different build system, you will need to execute `make` in the `libretro` subdirectory. This should solve your problems.
