### ISSUE TITLE
bsnes-jg core fails to open with (null) error

### ISSUE THREAD

**Issue by apteryks** [libretro/bsnes-jg#2]
Hi,

Attempting to load the core built from this project with the either 1.19.0 or latest RetroArch, I get:
```
[ERROR] Échec de l'ouverture du cœur Libretro: "/gnu/store/iljgnpqrvcafvva593dpx1wsdszfxri2-profile/lib/libretro/bsnes.so"
[ERROR] Error(s): (null)
```

The french message basically says "Failed to open the Libretro core: ...", with a not too useful error (or lack of?) reported as `(null)`.

Am I missing something important?

**Comment by carmiker** [comment]
Solved by #1
