### ISSUE TITLE
Overscan Cropping

### ISSUE THREAD

**Issue by James-F2** [libretro/bsnes-jg#5]
Bottom 8 pixels are cropped even with "Mask Overscan (Bottom)" setting is set to 0.

Using 240p Suite, GRID test pattern. https://artemiourbina.itch.io/240p-test-suite
Snes9x (and real SNES for that matter) do not crop when vertical overscan masking is set to 0.

![cropped0](https://github.com/user-attachments/assets/4eda4df5-8b11-4160-aa75-23be6873886e)

![cropped1](https://github.com/user-attachments/assets/4a411fb6-6c14-4891-894a-d5b6a5ac5b37)

![cropped2](https://github.com/user-attachments/assets/31070d23-c696-4897-9e3e-363ee221a4a9)

**Comment by carmiker** [comment]
Fixed.
